import { Allow, IsArray, IsBoolean, IsEnum, IsIn, IsOptional, IsString } from 'class-validator';
import { PlannedKind, TxnDirection } from '@prisma/client';
export class BankAccountDto { @IsString() bankName: string; @IsString() alias: string; @IsOptional() @IsString() accountNoMasked?: string; @IsOptional() @IsString() departmentId?: string | null; @IsOptional() @IsString() purpose?: string; @IsOptional() @IsBoolean() isRestricted?: boolean; @IsOptional() openingBalance?: string | number; @IsOptional() @IsString() openingDate?: string; @IsOptional() @IsBoolean() isActive?: boolean;
  /** 팝빌 계좌조회 연동 — 기관코드(4자리)와 계좌번호(하이픈 없이) */
  @IsOptional() @IsString() popbillBankCode?: string | null; @IsOptional() @IsString() popbillAccountNumber?: string | null; }
export class BankTxnRowDto { @IsString() txnAt: string; @IsEnum(TxnDirection) direction: TxnDirection; @Allow() amount: string | number; @IsOptional() @IsString() counterpartyRaw?: string; @IsOptional() @IsString() descriptionRaw?: string; @IsOptional() balanceAfter?: string | number; @IsOptional() @IsString() externalId?: string; }
export class ImportDto { @IsString() bankAccountId: string; @IsArray() rows: BankTxnRowDto[]; }
export class ReserveDto { @IsString() category: string; @IsString() purpose: string; @Allow() amount: string | number; @IsOptional() @IsString() memo?: string; @IsOptional() @IsString() reason?: string; }
export class ReserveMoveDto { @IsIn(['INCREASE', 'RELEASE']) type: 'INCREASE' | 'RELEASE'; @Allow() amount: string | number; @IsString() reason: string; }
export class PlannedDto { @IsEnum(PlannedKind) kind: PlannedKind; @IsString() title: string; @IsOptional() @IsString() category?: string; @Allow() amount: string | number; @IsString() dueDate: string; @IsOptional() @IsString() businessTypeId?: string; @IsOptional() @IsString() departmentId?: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsString() memo?: string; }
export class PlannedIncomeDto { @IsString() title: string; @Allow() amount: string | number; @IsString() dueDate: string; @IsOptional() @IsString() memo?: string; }

/** 수정용은 반드시 클래스여야 ValidationPipe가 동작한다 (Partial<>/any는 검증이 통째로 건너뛰어짐) */
export class UpdatePlannedIncomeDto { @IsOptional() @IsString() title?: string; @IsOptional() amount?: string | number; @IsOptional() @IsString() dueDate?: string; @IsOptional() @IsString() memo?: string; @IsOptional() @IsIn(['SCHEDULED', 'RECEIVED', 'CANCELLED']) status?: string; }
export class UpdatePlannedDto { @IsOptional() @IsEnum(PlannedKind) kind?: PlannedKind; @IsOptional() @IsString() title?: string; @IsOptional() @IsString() category?: string; @IsOptional() amount?: string | number; @IsOptional() @IsString() dueDate?: string; @IsOptional() @IsString() businessTypeId?: string; @IsOptional() @IsString() departmentId?: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsString() memo?: string; @IsOptional() @IsIn(['PLANNED', 'CONFIRMED', 'PAID', 'CANCELLED']) status?: string; }
export class UpdateBankAccountDto { @IsOptional() @IsString() bankName?: string; @IsOptional() @IsString() alias?: string; @IsOptional() @IsString() accountNoMasked?: string; @IsOptional() @IsString() departmentId?: string | null; @IsOptional() @IsString() purpose?: string; @IsOptional() @IsBoolean() isRestricted?: boolean; @IsOptional() openingBalance?: string | number; @IsOptional() @IsString() openingDate?: string; @IsOptional() @IsBoolean() isActive?: boolean; @IsOptional() @IsString() popbillBankCode?: string | null; @IsOptional() @IsString() popbillAccountNumber?: string | null; }
